package model;
// Generated 24 févr. 2015 21:04:44 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Demandecarte generated by hbm2java
 */
public class Demandecarte  implements java.io.Serializable {


     private Integer idDemandeCarte;
     private Date dateDemandeCarte;
     private String typeCarte;
     private String etatCarte;
     private Date dateDelivrance;
     private int numCompte;

    public Demandecarte() {
    }

    public Demandecarte(Date dateDemandeCarte, String typeCarte, String etatCarte, Date dateDelivrance, int numCompte) {
       this.dateDemandeCarte = dateDemandeCarte;
       this.typeCarte = typeCarte;
       this.etatCarte = etatCarte;
       this.dateDelivrance = dateDelivrance;
       this.numCompte = numCompte;
    }
   
    public Integer getIdDemandeCarte() {
        return this.idDemandeCarte;
    }
    
    public void setIdDemandeCarte(Integer idDemandeCarte) {
        this.idDemandeCarte = idDemandeCarte;
    }
    public Date getDateDemandeCarte() {
        return this.dateDemandeCarte;
    }
    
    public void setDateDemandeCarte(Date dateDemandeCarte) {
        this.dateDemandeCarte = dateDemandeCarte;
    }
    public String getTypeCarte() {
        return this.typeCarte;
    }
    
    public void setTypeCarte(String typeCarte) {
        this.typeCarte = typeCarte;
    }
    public String getEtatCarte() {
        return this.etatCarte;
    }
    
    public void setEtatCarte(String etatCarte) {
        this.etatCarte = etatCarte;
    }
    public Date getDateDelivrance() {
        return this.dateDelivrance;
    }
    
    public void setDateDelivrance(Date dateDelivrance) {
        this.dateDelivrance = dateDelivrance;
    }
    public int getNumCompte() {
        return this.numCompte;
    }
    
    public void setNumCompte(int numCompte) {
        this.numCompte = numCompte;
    }




}


